name: build & testing

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    strategy:
       fail-fast: false
       matrix:
         node: [18, 20, 21]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}

      - name: Npm Install
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run Test
        run: npm run test
